export default {
  connect: false,
  vendorId: 0,
  productId: 0,
  manufacturer: '',
  product: '',
  serialNumber: '',
  majorVersion: 0,
  minorVersion: 0,
  patchVersion: 0,
  bootloaderMode: false,
  firmwarePresent: false,
  model: '',
  msg: null,
  xpub: '',
  label: '',
  passphraseProtection: false,
  initialized: true,
  needsBackup: null,
  err: null
}
